logs:
  error:
    output: ./error.log
    level: DEBUG
    traceoffset: 10
  main:
    output: ./main.log-*-*-*
    level: INFO

s-redis:
  default:
    Addr: 127.0.0.1:6379,127.0.0.1:6379,127.0.0.1:6379
    Password: '123456'
    MaxActive: 128
    MaxIdle: 16
    IdleTimeout: 240s
    ConnectTimeout: 500ms
    ReadTimeout: 500ms
    WriteTimeout: 1000ms
    TestInterval: 60s
  main:
    Addr: 127.0.0.1:6379,127.0.0.1:6379,127.0.0.1:6379
    Password: '123456'
    MaxActive: 128
    MaxIdle: 16
    IdleTimeout: 240s
    ConnectTimeout: 500ms
    ReadTimeout: 500ms
    WriteTimeout: 1000ms
    TestInterval: 60s

mydefine:
  - 123
  - 456
  - 789
